config/routes.rb
Rails.application.routes.draw do
  mount Rich::Engine => '/rich', :as => 'rich'
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :orders
  resources :units
  resources :articles, only: [:create, :edit, :update, :destroy]
  
  namespace :admin do
    resources :users, :orders, :units, :articles
  end
  
  root 'welcome#index'
  
  
  # LOGIN
  #match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  #match 'auth/failure', to: redirect('/'), via: [:get, :post]
  #match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]
  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  #match 
  
  # QnA
  match '/question/:type', to: 'articles#new', via: 'get'
  match '/question/:type/:order_id', to: 'articles#new', via: 'get'
  match '/article/:id/answer', to: 'articles#answer', via: 'get'
  
  # ORDERING
  match '/ordering', to: 'orders#new', via: 'get'
  
  # WELCOME
  match '/pricing', to: 'orders#pricing', via: 'get'
  match '/qna', to: 'articles#qna', via: 'get'
  
  # ADMIN PAGE
  match '/admin', to: 'admin/admin#index', via: 'get'

  # FOOTER
  match '/policy', to: 'welcome#policy', via: 'get'
  match '/privacy', to: 'welcome#privacy', via: 'get'
end

app/models/unit.rb
class Unit < ActiveRecord::Base
  
  PRICE = {default: 9900}
  TYPES = [:carrier, :regular, :hard]
  UNIT_RANGE = (1..10).to_a
  UNIT_IMAGE = { carrier: "/assets/welcome/storage-1.png",
               regular: "/assets/welcome/storage-2.png",
               hard: "http://goo.gl/NOC18R" }
  
  belongs_to :order
  
  has_attached_file :img,
    styles: { medium: "200x200>", thumb: "32x32>" },
    :default_url => "/images/:style/missing.png"

  validates_attachment :img, presence: true,
  content_type: { content_type: ["image/jpeg", "image/gif", "image/png"] },
  size: { in: 0.. 2.megabytes }
  
  validates :order_id, presence: true
  validates :unit_type, presence: true
  
end

app/controllers/admin/units_controller.rb
class Admin::UnitsController < ApplicationController
  before_action :admin_user
  
  def new
    @unit = Unit.new(order_id: params[:format])
  end

  def create
    @unit = Unit.new(unit_params)
    
    if @unit.save
      flash[:success] = "New unit created!"
      redirect_to @unit.order
    else
      flash[:warning] = "Creating failed.."
      render 'new'
    end
  end
  
  def edit
    @unit = Unit.find(params[:id])
  end
  
  def update
    @unit = Unit.find(params[:id])
    if @unit.update_attributes(unit_params)
      flash[:success] = "Unit updated"
      redirect_to @unit.order
    else
      render 'edit'
    end
  end
  
  def destroy
    @unit = Unit.find(params[:id])
    @unit.destroy
    flash[:success] = "Unit deleted."
    redirect_back_or order_path(@unit.order)
  end

  ########################
    def unit_params
      params.require(:unit).permit(:name, :content, :unit_type, :order_id, :img)
    end
  ########################
end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
  #before_action :correct_user_in_order
  
  #################################################
  def unit_params
    
  end
  
  def correct_user_in_order
     
  end
  #################################################
end

app/helpers/admin/units_helper.rb
module Admin::UnitsHelper
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/views/admin/units/edit.html.erb
<% provide(:title, "유닛 수정") %>
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <%= form_for @unit, url: admin_unit_path(@unit), method: :patch do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <div class="form-group">
        <label for="unit_name">유닛 타입</label>
        <%= select_tag("unit[unit_type]", options_for_select(Unit::UNIT_IMAGE.keys), prompt: "타입", class: "form-control input-lg") %>
      </div>
      <div class="form-group">
        <label for="unit_name">유닛 이름</label>
        <%= text_field(:unit, :name, class: "form-control input-lg", placeholder: "여행용캐리어")%>
      </div>
      <div class="form-group">
        <label for="unit_content">내용물 간단설명</label>
        <%= text_area(:unit, :content, class: "form-control input-lg", placeholder: "간략히 적어주세요")%>
      </div>
      
      <div class="form-group">
        <label for="unit_ex_img">이전 사진</label>
        <%= image_tag(@unit.img.url(:medium), alt: @unit.unit_type, class: "unit") %>
      </div>
    
      <div class="form-group">
        <label for="unit_img">유닛 사진</label>
        <%= f.file_field :img %>
        <p class="help-block">Example block-level help text here.</p>
      </div>
      <%= hidden_field(:unit, :order_id) %>
      <button type="submit" class="btn btn-lg btn-success">수정</button>
    <% end %>
  </div>
</div>

app/views/admin/units/new.html.erb
<% provide(:title, "유닛 생성") %>
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <%= form_for @unit, url: admin_units_path<<'.'<<params[:format] do |f| %>
    <div class="form-group">
      <label for="unit_name">유닛 타입</label>
      <%= select_tag("unit[unit_type]", options_for_select(Unit::UNIT_IMAGE.keys), prompt: "타입", class: "form-control input-lg") %>
    </div>
    <div class="form-group">
      <label for="unit_name">유닛 이름</label>
      <%= text_field(:unit, :name, class: "form-control input-lg", placeholder: "여행용캐리어")%>
    </div>
    <div class="form-group">
      <label for="unit_content">내용물 간단설명</label>
      <%= text_area(:unit, :content, class: "form-control input-lg", placeholder: "간략히 적어주세요")%>
    </div>
    <div class="form-group">
      <label for="unit_image">유닛 사진</label>
      <%= f.file_field :picture %>
      <p class="help-block">Example block-level help text here.</p>
    </div>
    <%= hidden_field(:unit, :order_id) %>
    <button type="submit" class="btn btn-lg btn-success">생성</button>
    <% end %>
  </div>
</div>