config/routes.rb
Rails.application.routes.draw do
  mount Rich::Engine => '/rich', :as => 'rich'
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :orders
  resources :units
  resources :articles, only: [:create, :edit, :update, :destroy]
  
  namespace :admin do
    resources :users, :orders, :units, :articles
  end
  
  root 'welcome#index'
  
  
  # LOGIN
  #match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  #match 'auth/failure', to: redirect('/'), via: [:get, :post]
  #match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]
  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  #match 
  
  # QnA
  match '/question/:type', to: 'articles#new', via: 'get'
  match '/question/:type/:order_id', to: 'articles#new', via: 'get'
  match '/article/:id/answer', to: 'articles#answer', via: 'get'
  
  # ORDERING
  match '/ordering', to: 'orders#new', via: 'get'
  
  # WELCOME
  match '/pricing', to: 'orders#pricing', via: 'get'
  match '/qna', to: 'articles#qna', via: 'get'
  
  # ADMIN PAGE
  match '/admin', to: 'admin/admin#index', via: 'get'

  # FOOTER
  match '/policy', to: 'welcome#policy', via: 'get'
  match '/privacy', to: 'welcome#privacy', via: 'get'
end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  belongs_to :order
  
  TYPES = { "질문/답변" => 0, # 질문/답변
            "이용후기" => 1} # 후기
  
  #default scope
  default_scope -> { order('created_at DESC') }
  
  #validates
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 500 }
  
  
end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < ApplicationController
  before_action :admin_user
  
  def index
    @questions = Article.where(types: 0).where.not(order_id: nil) # 0: 질문답변
  end
  
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :signed_in_user, except: [:index, :show, :qna]
  before_action :owner_or_admin, only: [:edit, :update, :destroy]
  before_action :admin_user, only: [:answer]
  
  def qna
    @questions = Article.where({types: 0, order_id: nil}) # 0: 질문답변
  end
  
  def answer
    @article = Article.find(params[:id])
    @article.answered = true
    render 'edit'
  end

  def new
    @article = Article.new(types: params[:type], order_id: params[:order_id])
  end

  def create
    @article = current_user.articles.build(article_params)
#    @data = @article
#    render 'test/test'

    if @article.save
      flash[:success] = "Created!"
      redirect_back_or '/qna'
    else
      flash.now[:success] = "Failed.."
      render 'new'
    end
  end
  
  def edit
    @article = Article.find(params[:id])
  end
  
  def update
    @article = Article.find(params[:id])
    
    if @article.update_attributes(article_params)
      flash[:success] = '수정 완료 되었습니다.'
      redirect_back_or '/qna'
    else
      render 'edit'
    end
  end
  
  def destroy
    Article.find(params[:id]).destroy
    flash[:success] = "Question deleted.."
    redirect_back_or '/qna'
  end
  
  private
    def article_params
      article_params = params.require(:article).permit(
        :types, :title, :content, :answered, :order_id)
    end
    
    def owner_or_admin
      unless owner? || current_user.admin?
        flash[:warning] = "직접 신청한 주문서 이외는 볼수 없습니다"
        redirect_to(root_url)
      end
    end
  
    def owner?
      @article = Article.find(params[:id])
      current_user?(User.find_by(id: @article.user_id))
    end
  
end

app/helpers/admin/articles_helper.rb
module Admin::ArticlesHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
  
  def questions(order)
    questions = Article.where({order_id: order.id, types: 0})
  end
end

app/views/articles/_faq.html.erb
<div class="panel panel-primary">
  <!-- Default panel contents -->
  <div class="panel-heading"><strong>자주하는 질문</strong></div>

  <table class="table table-striped">
    <tbody id="faq">
      <tr>
        <td data-toggle="collapse" data-parent="#faq" data-target="#1"><a><strong>Q. 물품보관은 안전한가요?</strong></a></td>
      </tr>
      <tr id="1" class="collapse faq-answer">
        <td>
          <p><strong>고객님의 소중한 물품은 안전하게 보관되고 있습니다.</strong></p>
          <p>1. 보안 테이프로 물품을 봉인(고객 요청시, 테이프를 제거하면 색상 변경)</p>
          <p>2. 물품 보관 박스에 보관(고객 요청시, 타인이 개봉 불가)</p>
          <p>3. 건물 자체 경비, 전문 방법 경비 업체 서비스</p>
          <p>4. 건물 보안, 창고 내 외부 보안, 개인 물품 보안 시스템 </p>
          <p>5. 24 시간 365일 CCTV 및 동작 감지기 작동</p>
          <p>아이엠박스 물품보관은 상기 5단계 이상의 보안 시스템이 적용됩니다. </p>
          <p>안심하시고, 물품을 보관하셔도 됩니다.</p>
          <p># 아이엠박스 보관창고는 물품 화재, 도난, 파손 보험에 가입되어 있습니다.</p>
        </td>
      </tr>

      <tr>
        <td data-toggle="collapse" data-parent="#faq" href="#2"><a><strong>Q. 물품 픽업 / 회송은 어떻게 진행되나요?</strong></a></td>
      </tr>
      <tr class="collapse faq-answer" id="2">
        <td>
          <p>아이엠박스 물품 배송은 2가지 방법으로 이루어 집니다. </p>
          <p><strong>1. 아이엠박스 배송팀 픽업 / 배송(서울, 경기 지역)</strong></p>
          <p>① 고객님의 일정 / 위치 등을 저희 배송팀과 협의한 후 , 고객님의 물품을 운송합니다. </p>
          <p>② 당일 배송 / 회송이 가능합니다. </p>
          <p>③ 원하시는 시간에 저희 배송팀이 고객님이 계시는 곳 까지 방문합니다.</p>
          <p><strong>2. 택배사를 이용한 배송(서울, 경기 지역 제외)</strong></p>
          <p>① 당일 배송 / 회송이 불가합니다.</p>
          <p>② 고객님이 원하시는 시간과 다소 차이가 발생할 수 있습니다. </p>
          <p>아이엠박스는 상기 2가지 방법으로 배송 / 회송이 이루어 집니다. </p>
          <p>감사합니다</p>
        </td>
      </tr>

      <tr>
        <td data-toggle="collapse" data-parent="#faq" href="#3"><a><strong>Q. 주말에도 픽업 / 회송이 가능한가요?</strong></a></td>
      </tr>
      <tr class="collapse faq-answer" id="3">
        <td>
          <p>픽업 및 회송은 <strong>토요일 오전 까지 가능합니다.</strong></p>
          <p>고객님께 도착하는 시간을 기준으로 낮 12:00 까지 픽업 및 회송이 가능합니다.</p>
          <p>이점 양해 부탁드립니다. </p>
          <p>그리고, <strong>공휴일 및 주일은 쉽니다.</strong></p>
          <p>감사합니다.</p>
        </td>
      </tr>

      <tr>
        <td data-toggle="collapse" data-parent="#faq" href="#4"><a><strong>Q. 물품(짐)도 운반해 주나요?</strong></a></td>
      </tr>
      <tr class="collapse" id="4">
        <td>
          <p><strong>내부 규정상 픽업 및 회송시 물품(짐)을 들어드리지 않습니다.</strong></p>
          <p>픽업 및 회송시 고객님께서 물품(짐)을 운반하셔야 하며, 간단한 운반정도는 저희가 도와드리고 있습니다.</p>
          <p><strong>물품이 많거나, 무거운 짐이 있으시다면 추가 인력을 요청하셔야 하며, 추가 운임을 청구 됩니다.</strong></p>
          <p>감사합니다.</p>
        </td>
      </tr>

      <tr>
        <td data-toggle="collapse" data-parent="#faq" href="#5"><a><strong>Q. 보관된 물품의 현황(상태)를 확인할 수 있나요?</strong></a></td>
      </tr>
      <tr class="collapse faq-answer" id="5">
        <td>
          <p>고객님이 맡기신 물품은,</p>
          <p>아이엠박스 물품보관 창고로 옮긴 후 사진을 찍어 고객님께 보내드립니다.</p>
          <p>물품 보관 이후에는 고객님의 요청없이는 절대 박스 및 물품을 개봉하지 않습니다.</p>
          <p>현재, 고객님의 보관 상태를 쉽게 확인하실 수 있는 시스템을 개발 중입니다.</p>
          <p># 24시간, 365일 적정온도 및 습도를 유지하기 때문에 습도 및 부패의 걱정이 없습니다.</p>
        </td>
      </tr>

      <tr>
        <td data-toggle="collapse" data-parent="#faq" href="#6"><a><strong>Q. 경기도 / 인천공항(김포공항)도 픽업 및 회송이 되나요?</strong></a></td>
      </tr>
      <tr class="collapse faq-answer" id="6">
        <td>
          <p><strong>경기도 / 인천 공항도 픽업 및 회송이 가능합니다.</strong></p>
          <p>다만 거리에 따라 <strong>추가 요금</strong>이 발생한다는 점을 미리 말씀 드립니다.</p>
          <p>경기도는 서울 배송비 (14,900원)의 1.5배 ~ 2배의 운송비가 청구 됩니다.</p>
          <p>인천 공항도 추가 요금이 발생합니다.</p>
          <p>서울 및 경기도에서 물품을 맡기고, 인천공항 / 김포공항에서 물품을 받으셔도 됩니다.</p>
          <p>또는 인천공항 / 김포공항에서 물품을 픽업한 후, 서울 및 경기도에서도 물품을 받아보실 수 있습니다.</p>
          <p>감사합니다.</p>
        </td>
      </tr>

      <tr>
        <td data-toggle="collapse" data-parent="#faq" href="#7"><a><strong>Q. 제주도 물품보관이 가능하나요 ?</strong></a></td>
      </tr>
      <tr class="collapse faq-answer" id="7">
        <td>
          <p><strong>제주도 물품보관이 가능합니다.</strong></p>
          <p>제주도는 저희 <a href="tel:02-6091-8008">고객센터(02-6091-8008)</a>로 연락주시면 친절하게 안내해 드리겠습니다.</p>
          <p>당일 물품 픽업은 스케줄 등의 관계로 어려울 수 있으니, 사전에 미리 연락주시면 감사하겠습니다.</p>
        </td>
      </tr>

      <tr>
        <td data-toggle="collapse" data-parent="#faq" href="#8"><a><strong>Q. 물품보관 비용은 주 단위로만 책정 되나요 ?</strong></a></td>
      </tr>
      <tr class="collapse faq-answer" id="8">
        <td>
          <p><strong>저희 아이엠박스 물품보관 서비스는 주 단위로 보관 비용이 책정 됩니다. </strong></p>
          <p>만약에 15일을 맡기게 되신다면, 이런 경우는 2주로 가격이 적용됩니다. (2주 +1일)</p>
          <p>1주일에서 이틀이상 넘게 되면, 주 단위로 가격이 책정된다는 점 양해 부탁드립니다.</p>
          <p>감사합니다.</p>
        </td>
      </tr>

    </tbody>
  </table>
</div>

app/views/articles/_qna.html.erb
<% if questions.any? %>
<div class="panel panel-<%= defined?(order) ? 'default' : 'primary' %>" id="qna">
  <!-- Default panel contents -->
  <div class="panel-heading"><strong>질문 - 답변</strong></div>

  <table class="table table-striped">
    <thead>
      <tr>
        <th>질문</th>
        <th>작성자</th>
        <th>등록일</th>
      </tr>
    </thead>

    <tbody>
      <% questions.each do |question| %>
      <%= render 'articles/question', q: question %>
      <% end %>
    </tbody>
  </table>
</div>
<% end %>
<% if defined? order %>
<%= link_to "질문하기", "/question/0/#{order.id}", class: "btn btn-sm btn-primary pull-left col-md-1" %>
<% else %>
<%= link_to "질문하기", '/question/0', class: "btn btn-lg btn-primary pull-right" %>
<% end %>

app/views/articles/_question.html.erb
<tr>
  <td class="col-sm-9" data-toggle="collapse" data-parent="#qna" data-target="#qna-<%= q.id %>">
    <a><strong><%= q.title %> <%= bs_label(q.answered ? "답변완료" : "New") %></strong></a>
  </td>
  <td class="col-sm-1"><%= link_to(q.user.name, current_user.admin? ? q.user : '#') %></td>
  <td class="col-sm-2"><%= q.updated_at.strftime("%Y-%m-%d") %></td>
</tr>
<tr id="qna-<%= q.id %>" class="collapse">
  <td colspan="3">
    <p><%= simple_format(q.content) %></p>
    <p>
      <% if current_user && current_user.admin? %>
      <%= link_to bs_label('답변하기', 'success'), "/article/#{q.id}/answer" %>
      <% end %>
      <% if current_user && (current_user == q.user || current_user.admin?) %>
        <%= link_to bs_label('수정', 'info'), edit_article_path(q) %>
        <%= link_to bs_label('삭제', 'danger'), article_path(q), method: :delete, data: { confirm: 'Are you sure?' } %>
      <% end %>
    </p>
  </td>
</tr>

app/views/articles/edit.html.erb
<% provide(:title, "질문하기") %>
<div class="row">
  <div class="col-sm-8 col-sm-offset-2">
    <%= form_for @article do |f| %>
    <div class="form-group">
      <%= f.label :types, "타입" %>
      <%= f.select(:types, options_for_select(Article::TYPES, selected: @article.types), {}, class: "form-control input-lg", disabled: true) %>
      <%= f.hidden_field(:types) %>
      <%= f.hidden_field(:answered) %>
    </div>

    <div class="form-group">
      <%= f.label :title, "제목" %>
      <%= f.text_field :title, class: "form-control input-lg", placeholder: "제목을 적어주세요" %>
    </div>

    <div class="form-group">
      <%= f.label :content, "내용" %>
      <%= f.text_area :content, rows: 10, class: "form-control input-lg", placeholder: "내용을 적어주세요" %>
    </div>
      <%= f.submit "수정완료", class: "btn btn-lg btn-primary pull-right" %>
    <% end %>  
  </div>
</div>

app/views/articles/new.html.erb
<% provide(:title, "질문하기") %>
<div class="row">
  <div class="col-sm-8 col-sm-offset-2">
    <%= form_for @article do |f| %>
    <div class="form-group">
      <%= f.label :types, "타입" %>
      <%= f.select(:types, options_for_select(Article::TYPES, selected: @article.types), {}, class: "form-control input-lg", disabled: true) %>
      <%= f.hidden_field(:types) %>
      <%= f.hidden_field(:order_id) %>
    </div>

    <div class="form-group">
      <%= f.label :title, "제목" %>
      <%= f.text_field :title, class: "form-control input-lg", placeholder: "제목을 적어주세요" %>
    </div>

    <div class="form-group">
      <%= f.label :content, "내용" %>
      <%= f.text_area :content, rows: 10, class: "form-control input-lg", placeholder: "내용을 적어주세요" %>
    </div>
      <%= f.submit "작성완료", class: "btn btn-lg btn-primary pull-right" %>
    <% end %>  
  </div>
</div>

app/views/articles/qna.html.erb
<% provide(:title, "질문") %>
<div class="row">
  <div class="col-sm-12 col-md-10 col-md-offset-1 col-lg-8 col-lg-offset-2">
    <%= render 'articles/faq' %>
    <%= render 'articles/qna', {questions: @questions} %>
  </div>
</div>