config/routes.rb
Rails.application.routes.draw do
  mount Rich::Engine => '/rich', :as => 'rich'
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :orders
  resources :units
  resources :articles, only: [:create, :edit, :update, :destroy]
  
  namespace :admin do
    resources :users, :orders, :units, :articles
  end
  
  root 'welcome#index'
  
  
  # LOGIN
  #match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  #match 'auth/failure', to: redirect('/'), via: [:get, :post]
  #match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]
  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  #match 
  
  # QnA
  match '/question/:type', to: 'articles#new', via: 'get'
  match '/question/:type/:order_id', to: 'articles#new', via: 'get'
  match '/article/:id/answer', to: 'articles#answer', via: 'get'
  
  # ORDERING
  match '/ordering', to: 'orders#new', via: 'get'
  
  # WELCOME
  match '/pricing', to: 'orders#pricing', via: 'get'
  match '/qna', to: 'articles#qna', via: 'get'
  
  # ADMIN PAGE
  match '/admin', to: 'admin/admin#index', via: 'get'

  # FOOTER
  match '/policy', to: 'welcome#policy', via: 'get'
  match '/privacy', to: 'welcome#privacy', via: 'get'
end

app/models/order.rb
class Order < ActiveRecord::Base
  
  belongs_to :user
  has_many :units, dependent: :destroy
  has_many :articles
  
  STATUS = {ordered: 0, # 주문완료
            permitted: 1, # 승인(입금)완료
            picking_up: 2, # 픽업중
            stored: 3, # 보관중
            delivering: 4, # 회송중
            delivered: 5, # 회송완료
            deleted: -1,} # 삭제됨
  
  WHY_ORDERING = ["물품보관","이사", "여행", "출국", "기타"] 
  
  LOCATION = [["서울", 0], ["경기", 15000] , ["인천공항", 35000]]
  AVAILABLE_MEETING_TIMES = [["10시-13시",10], ["13시-16시", 13], ["16시-19시", 16]]
  
  #default scope
  default_scope -> { order('created_at DESC') }
  
  validates :user_id, presence: true
  validates :unit_count, presence: true, numericality: { greater_than: 0 }
  validates :units_info, presence: true
  validates :store_weeks, presence: true
  validates :charge, presence: true
  validates :pickup_datetime, presence: true
  validates :delivery_datetime, presence: true
  validates :pickup_location, presence: true
  validates :pickup_address, presence: true, length: { maximum: 100 }
  validates :delivery_location, presence: true
  validates :delivery_address, presence: true, length: { maximum: 100 }
  validates :why_ordering, presence: true, length: { maximum: 20 }
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :admin_user
  
  def index
    @orders = Order.all
  end
  
  def update # 주문의 STATUS를 다음단계로 진행한다
    @order = Order.find(params[:id])
    status = @order.status.to_i + 1
    
    if @order.update_attributes(status: status)
      flash[:success] = "Orders Status incresed"
      redirect_back_or admin_path
    else
      redirect_back_or admin_path
    end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :signed_in_user, except: [:pricing]
  before_action :owner_or_admin, only: [:show, :edit, :update, :destroy, :checked]
  
  include OrdersHelper

  def index
    
  end
  
  def pricing
    @pricing = pricing_order_params
    
#    render 'test/test'
#    render 'welcome/pricing/_result'
    respond_to do |format|
      format.js
    end
  end
  
  def new
    @order = Order.new
  end
  
  def create
    @order = current_user.orders.build(order_params)
    
    if @order.save
      flash[:success] = t 'controller.orders.create.please_check'
      redirect_to @order
    else
      flash.now[:warning] = t 'controller.orders.create.failed'
      render 'new'
    end
  end
  
  def show
    @order = Order.find(params[:id])
    @units = @order.units
  end
  
  def edit
    @order = Order.find(params[:id])
    updating_deny if (@order.status != 0 && !current_user.admin?)
  end
  
  def update
    @order = Order.find(params[:id])
    updating_deny if (@order.status != 0 && !current_user.admin?)
    
    if @order.update_attributes(order_params)
      flash[:success] = t 'controller.orders.update.succeed'
      redirect_to @order
    else
      render 'edit'
    end
  end
  
  def destroy
    @order = Order.find(params[:id])
    
    if @order.status == 0
      @order.update_attributes(status: -1)
      flash[:success] = t 'controller.orders.destroy.succeed'
      redirect_back_or current_user.admin? ? admin_path : current_user
    else
      flash[:warning] = t 'controller.orders.destroy.failed'
    end
  end
  
  private ########################################
    def order_params
      raw_params = params.require(:order).permit(
        {unit_count: [:carrier, :regular, :hard]},
        {pickup_datetime: [:year, :month, :day, :hour]},
        {delivery_datetime: [:year, :month, :day, :hour]},
        :pickup_address, :pickup_location,
        :delivery_address, :delivery_location,
        :why_ordering, :extra_checked)
      
      raw_params.has_key?("extra_checked") ? raw_params : order_params = filtered_order(raw_params)
    end
  
    def order_attributes(attributes)
      attributes.permit(
        :unit_count,
        :pickup_datetime,
        :delivery_datetime,
        :pickup_address,
        :delivery_address,
        :why_ordering)
    end
  
    def unit_count
      params.require(:order).permit(
        {unit_count: [:carrier, :regular, :hard]})
    end

    def units
      @unit_array = Array.new
    end
    
    def create_units(unit_params)
      unit_params[:unit_count].each do |type, count|
        count.to_i.times do
          @unit = @order.units.build(unit_type: type)
          @unit.save
        end
      end
    end
  
    def owner_or_admin
      unless owner? || current_user.admin?
        flash[:warning] = "직접 신청한 주문서 이외는 볼수 없습니다"
        redirect_to(root_url)
      end
    end
  
    def owner?
      @order = Order.find(params[:id])
      current_user?(User.find_by(id: @order.user_id))
    end
  
    def updating_deny
      flash[:warning] = "이미 승인된 내용을 수정할 수 없습니다."
      redirect_back_or(root_path) 
    end
  
  def pricing_order_params
    raw_params = params.require(:order).permit(
        :unit_count,
        {pickup_datetime: [:year, :month, :day]},
        {delivery_datetime: [:year, :month, :day]},
        :pickup_location,
        :delivery_location)
    
      pricing_order(raw_params)
  end
  
  def checked_params
    params.require(:order).permit(:extra_checked)
  end
  ################################################
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
  
  def unit_count(order, type)
    order.units_info.split(',')[Unit::TYPES.index(type.to_sym)].last if order.units_info
  end
  
  def pricing_order(order)
    #pickup_datetime
    order[:pickup_datetime] = Time.new(order[:pickup_datetime][:year],
      order[:pickup_datetime][:month],
      order[:pickup_datetime][:day])

    #delivery_datetime
    order[:delivery_datetime] = Time.new(order[:delivery_datetime][:year],
      order[:delivery_datetime][:month],
      order[:delivery_datetime][:day])
    
    #unit_count
    order[:unit_count] = order[:unit_count].to_i

    #store_weeks
    order[:store_weeks] = store_weeks(order[:pickup_datetime],
      order[:delivery_datetime])

    #weeks_discount
    order[:weeks_discount] = weeks_discount(order[:store_weeks])

    #unit_discount
    order[:unit_discount] = unit_discount(order[:unit_count])

    #locations
    order[:pickup_location] = order[:pickup_location].to_i
    order[:delivery_location] = order[:delivery_location].to_i

    #transport_price
    order[:transport_price] = transport_price(order[:pickup_location],
      order[:delivery_location])

    #charge(total_price)
    order[:storing_normal] = Unit::PRICE[:default] * order[:unit_count] * order[:store_weeks]
    total_dc = order[:unit_discount] + order[:weeks_discount]
    order[:charge] = order[:storing_normal] * (1 - total_dc) + order[:transport_price]
    order[:charge] = order[:charge].round(-2)

    #charge description
    order[:storing_discounted] = order[:charge] - order[:transport_price] 

    order
  end

  def filtered_order(order)
    #unit_count
    c_cnt = order[:unit_count][:carrier].to_i
    r_cnt = order[:unit_count][:regular].to_i
    h_cnt = order[:unit_count][:hard].to_i
    order[:unit_count] = c_cnt + r_cnt + h_cnt

    #units
    order[:units_info] =
      "carrier: #{c_cnt}, regular: #{r_cnt}, hard: #{h_cnt}"

    #pickup_datetime
    year = order[:pickup_datetime][:year]
    month = order[:pickup_datetime][:month]
    day = order[:pickup_datetime][:day]
    hour = order[:pickup_datetime][:hour]
    order[:pickup_datetime] = Time.new(year, month, day, hour, 0, 0, "+09:00")

    #delivery_datetime
    year = order[:delivery_datetime][:year]
    month = order[:delivery_datetime][:month]
    day = order[:delivery_datetime][:day]
    hour = order[:delivery_datetime][:hour]
    order[:delivery_datetime] = Time.new(year, month, day, hour, 0, 0, "+09:00")

    #store_weeks
    order[:store_weeks] = store_weeks(order[:pickup_datetime],
      order[:delivery_datetime])

    #weeks_discount
    weeks_dc = weeks_discount(order[:store_weeks])

    #unit_discount
    unit_dc = unit_discount(order[:unit_count])

    #locations
    order[:pickup_location] = order[:pickup_location].to_i
    order[:delivery_location] = order[:delivery_location].to_i

    #transport_price
    transport_price = transport_price(order[:pickup_location],
      order[:delivery_location])

    #charge(total_price)
    order[:charge] = 9900 * order[:unit_count].to_i * order[:store_weeks] * (1 - unit_dc + weeks_dc) + transport_price
    order[:charge] = order[:charge].round(-2)
    
    order
  end

  def collapse_panel(number, title, body)
    @panel = {
      number: number,
      title: title,
      body: body
      }
  end

  def collapse_panel_body(path, object = nil)
    @body = {
      path: path,
      object: object
      }
  end

  ######################################
  private
  def charge(unit_charge, unit_count, store_weeks, delivery_charge)
    charge = unit_charge * unit_count * store_weeks
    unless unit_count == 0
      count_discount = Math.log2(unit_count ** 9).ceil / 100.0
    else
      count_discount = 0
    end
    weeks_discount = (Math.log2(store_weeks) / 100.0).round(3)
    charge = charge * (1 - count_discount) * (1 - weeks_discount)
    charge += delivery_charge
    charge.round(-2)
  end

  def unit_discount(unit_count)
    unit_count = unit_count.to_i
    unless unit_count == 0
      unit_discount = Math.log2(unit_count ** 9).ceil / 100.0
    else
      unit_discount = 0
    end
  end

  def store_weeks(pickup_datetime, delivery_datetime)
    secs = delivery_datetime - pickup_datetime
    weeks = (secs <= 0) ? 1 : (secs / 60 / 60 / 24 / 7).ceil
  end

  def weeks_discount(weeks)
    #(Math.log2(weeks) / 100.0).round(3)
    discount = weeks < 4 ? 0.0 : ( (weeks < 20) ? 0.2 : 0.3 )
  end

  def transport_price(pickup_location, delivery_location)
    pickup_location.to_i + delivery_location.to_i + 29900
  end
  #######################################
end

app/views/admin/orders/_all.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
     모든 주문내역 <span class="badge"><%= all_orders.count %></span>
  </div>
  <div class="panel-body">
    <table class="table">
      <thead>
        <tr>
          <th><span class="glyphicon glyphicon-user"></span>사용자</th>
          <th><span class="glyphicon glyphicon-phone"></span>연락처</th>
          <th><span class="glyphicon glyphicon-calendar"></span>픽업일</th>
          <th><span class="glyphicon glyphicon-calendar"></span>회송일</th>
          <th><%= bs_icon(:time, "주문시간") %></th>
        </tr>
      </thead>

      <tbody>
        <% all_orders.each do |order| %>
        <tr>
          <td><%= link_to(order.user.name, user_path(order.user)) %></td>
          <td><%= order.user.phone %></td>
          <td><%= order.pickup_datetime.strftime("%Y-%m-%d %H(+3)") %></td>
          <td><%= order.delivery_datetime.strftime("%Y-%m-%d %H(+3)") %></td>
          <td><%= order.created_at.strftime("%Y-%m-%d %H:%M") %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/orders/_deleted.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    취소된 주문 <span class="badge"><%= deleted_orders.count %></span>
  </div>
  <div class="panel-body">
    <table class="table">
      <thead>
        <tr>
          <th><span class="glyphicon glyphicon-user"></span>사용자</th>
          <th><span class="glyphicon glyphicon-phone"></span>연락처</th>
          <th><span class="glyphicon glyphicon-calendar"></span>생성시간</th>
          <th><span class="glyphicon glyphicon-calendar"></span>삭제시간</th>
        </tr>
      </thead>

      <tbody>
        <% deleted_orders.each do |deleted_order| %>
        <tr>
          <td><%= link_to(deleted_order.user.name, user_path(deleted_order.user)) %></td>
          <td><%= deleted_order.user.phone %></td>
          <td><%= deleted_order.created_at.strftime("%Y-%m-%d %H:%M") %></td>
          <td><%= deleted_order.updated_at.strftime("%Y-%m-%d %H:%M") %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/orders/_delivered.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    회송 완료 <span class="badge"><%= delivered_orders.count %></span>
  </div>
  <div class="panel-body">
    <table class="table">
      <thead>
        <tr>
          <th><span class="glyphicon glyphicon-user"></span>사용자</th>
          <th><span class="glyphicon glyphicon-phone"></span>연락처</th>
          <th><span class="glyphicon glyphicon-calendar"></span>회송일</th>
          <th><span class="glyphicon glyphicon-home"></span>회송장소</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% delivered_orders.each do |delivered_order| %>
        <tr>
          <td><%= link_to(delivered_order.user.name, user_path(delivered_order.user)) %></td>
          <td><%= delivered_order.user.phone %></td>
          <td><%= delivered_order.delivery_datetime.strftime("%Y-%m-%d %H시(+3)") %></td>
          <td><%= delivered_order.delivery_address %></td>
          <td><%= link_to '회송완료', admin_order_path(delivered_order), method: :patch, class: 'btn btn-sm btn-success' %></td>
          <td><%= link_to '보기', order_path(delivered_order), class: 'btn btn-sm btn-default' %></td>
          <td><%= link_to '수정', edit_order_path(delivered_order), class: 'btn btn-sm btn-warning' %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/orders/_delivering.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    회송중 <span class="badge"><%= delivering_orders.count %></span>
  </div>
  <div class="panel-body">
    <table class="table">
      <thead>
        <tr>
          <th><span class="glyphicon glyphicon-user"></span>사용자</th>
          <th><span class="glyphicon glyphicon-phone"></span>연락처</th>
          <th><span class="glyphicon glyphicon-calendar"></span>회송일</th>
          <th><span class="glyphicon glyphicon-home"></span>회송장소</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% delivering_orders.each do |delivering_order| %>
        <tr>
          <td><%= link_to(delivering_order.user.name, user_path(delivering_order.user)) %></td>
          <td><%= delivering_order.user.phone %></td>
          <td><%= delivering_order.delivery_datetime.strftime("%Y-%m-%d %H시(+3)") %></td>
          <td><%= delivering_order.delivery_address %></td>
          <td><%= link_to '회송완료', admin_order_path(delivering_order), method: :patch, class: 'btn btn-sm btn-success' %></td>
          <td><%= link_to '보기', order_path(delivering_order), class: 'btn btn-sm btn-default' %></td>
          <td><%= link_to '수정', edit_order_path(delivering_order), class: 'btn btn-sm btn-warning' %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/orders/_ordered.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    신규 주문 <span class="badge"><%= new_orders.count %></span>
  </div>
  <div class="panel-body">
    <table class="table">
      <thead>
        <tr>
          <th><span class="glyphicon glyphicon-user"></span>사용자</th>
          <th><span class="glyphicon glyphicon-phone"></span>연락처</th>
          <th><span class="glyphicon glyphicon-calendar"></span>픽업일</th>
          <th><span class="glyphicon glyphicon-home"></span>픽업장소</th>
          <th><%= bs_icon(:time, "주문시간") %></th>
          <th colspan="4"></th>
        </tr>
      </thead>

      <tbody>
        <% new_orders.each do |new_order| %>
        <tr>
          <td><%= link_to(new_order.user.name, user_path(new_order.user)) %></td>
          <td><%= new_order.user.phone %></td>
          <td><%= new_order.pickup_datetime.strftime("%Y-%m-%d %H시(+3)") %></td>
          <td><%= new_order.pickup_address %></td>
          <td><%= new_order.updated_at.strftime("%Y-%m-%d %H:%M") %></td>
          <td><%= link_to '입금확인 및 문자전송', admin_order_path(new_order), method: :patch, class: 'btn btn-sm btn-success' %></td>
          <td><%= link_to '보기', order_path(new_order), class: 'btn btn-sm btn-default' %></td>
          <td><%= link_to '수정', edit_order_path(new_order), class: 'btn btn-sm btn-warning' %></td>
          <td><%= link_to '삭제', order_path(new_order), method: :delete, class: 'btn btn-sm btn-danger', data: { confirm: 'Are you sure?' } %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/orders/_permitted.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    픽업 대기 <span class="badge"><%= permitted_orders.count %></span>
  </div>
  <div class="panel-body">
    <table class="table">
      <thead>
        <tr>
          <th><span class="glyphicon glyphicon-user"></span>사용자</th>
          <th><span class="glyphicon glyphicon-phone"></span>연락처</th>
          <th><span class="glyphicon glyphicon-calendar"></span>픽업일</th>
          <th><span class="glyphicon glyphicon-home"></span>픽업장소</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% permitted_orders.each do |permitted_order| %>
        <tr>
          <td><%= link_to(permitted_order.user.name, user_path(permitted_order.user)) %></td>
          <td><%= permitted_order.user.phone %></td>
          <td><%= permitted_order.pickup_datetime.strftime("%Y-%m-%d %H시(+3)") %></td>
          <td><%= permitted_order.pickup_address %></td>
          <td><%= link_to '픽업출발', admin_order_path(permitted_order), method: :patch, class: 'btn btn-sm btn-success' %></td>
          <td><%= link_to '보기', order_path(permitted_order), class: 'btn btn-sm btn-default' %></td>
          <td><%= link_to '수정', edit_order_path(permitted_order), class: 'btn btn-sm btn-warning' %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/orders/_picking_up.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    픽업중 <span class="badge"><%= picking_up_orders.count %></span>
  </div>
  <div class="panel-body">
    <table class="table">
      <thead>
        <tr>
          <th><span class="glyphicon glyphicon-user"></span>사용자</th>
          <th><span class="glyphicon glyphicon-phone"></span>연락처</th>
          <th><span class="glyphicon glyphicon-calendar"></span>픽업일</th>
          <th><span class="glyphicon glyphicon-home"></span>픽업장소</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% picking_up_orders.each do |picking_up_order| %>
        <tr>
          <td><%= link_to(picking_up_order.user.name, user_path(picking_up_order.user)) %></td>
          <td><%= picking_up_order.user.phone %></td>
          <td><%= picking_up_order.pickup_datetime.strftime("%Y-%m-%d %H시(+3)") %></td>
          <td><%= picking_up_order.pickup_address %></td>
          <td><%= link_to '유닛등록 및 보관완료', admin_order_path(picking_up_order), method: :patch, class: 'btn btn-sm btn-success' %></td>
          <td><%= link_to '보기', order_path(picking_up_order), class: 'btn btn-sm btn-default' %></td>
          <td><%= link_to '수정', edit_order_path(picking_up_order), class: 'btn btn-sm btn-warning' %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/orders/_stored.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    보관중 <span class="badge"><%= stored_orders.count %></span>
  </div>
  <div class="panel-body">
    <table class="table">
      <thead>
        <tr>
          <th><%= bs_icon :user, "사용자" %></th>
          <th><%= bs_icon :phone, "연락처" %></th>
          <th><%= bs_icon :calendar, "회송일" %></th>
          <th><%= bs_icon :home, "회송장소" %></th>
          <th><%= bs_icon :briefcase, "보관품" %></th>
          <th></th>
        </tr>
      </thead>

      <tbody>
        <% stored_orders.each do |stored_order| %>
        <tr>
          <td><%= link_to(stored_order.user.name, user_path(stored_order.user)) %></td>
          <td><%= stored_order.user.phone %></td>
          <td><%= stored_order.delivery_datetime.strftime("%Y-%m-%d %H시(+3)") %></td>
          <td><%= stored_order.delivery_address %></td>
          <td><%= render 'units/thumb', order: stored_order %></td>
          <td>
            <%= link_to '회송출발', admin_order_path(stored_order), method: :patch, class: 'btn btn-sm btn-success' %>
            <%= link_to '보기', order_path(stored_order), class: 'btn btn-sm btn-default' %>
            <%= link_to '수정', edit_order_path(stored_order), class: 'btn btn-sm btn-warning' %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/orders/index.html.erb
<% provide(:title, '관리자모드') %>
<div class="row" id="admin">

  <%= render 'admin/shared/aside' %>

  <div class="col-sm-10">
    <%= render 'admin/orders/all', all_orders: @orders %>
  </div>

</div>