config/routes.rb
Rails.application.routes.draw do
  mount Rich::Engine => '/rich', :as => 'rich'
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :orders
  resources :units
  resources :articles, only: [:create, :edit, :update, :destroy]
  
  namespace :admin do
    resources :users, :orders, :units, :articles
  end
  
  root 'welcome#index'
  
  
  # LOGIN
  #match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  #match 'auth/failure', to: redirect('/'), via: [:get, :post]
  #match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]
  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  #match 
  
  # QnA
  match '/question/:type', to: 'articles#new', via: 'get'
  match '/question/:type/:order_id', to: 'articles#new', via: 'get'
  match '/article/:id/answer', to: 'articles#answer', via: 'get'
  
  # ORDERING
  match '/ordering', to: 'orders#new', via: 'get'
  
  # WELCOME
  match '/pricing', to: 'orders#pricing', via: 'get'
  match '/qna', to: 'articles#qna', via: 'get'
  
  # ADMIN PAGE
  match '/admin', to: 'admin/admin#index', via: 'get'

  # FOOTER
  match '/policy', to: 'welcome#policy', via: 'get'
  match '/privacy', to: 'welcome#privacy', via: 'get'
end

app/models/unit.rb
class Unit < ActiveRecord::Base
  
  PRICE = {default: 9900}
  TYPES = [:carrier, :regular, :hard]
  UNIT_RANGE = (1..10).to_a
  UNIT_IMAGE = { carrier: "/assets/welcome/storage-1.png",
               regular: "/assets/welcome/storage-2.png",
               hard: "http://goo.gl/NOC18R" }
  
  belongs_to :order
  
  has_attached_file :img,
    styles: { medium: "200x200>", thumb: "32x32>" },
    :default_url => "/images/:style/missing.png"

  validates_attachment :img, presence: true,
  content_type: { content_type: ["image/jpeg", "image/gif", "image/png"] },
  size: { in: 0.. 2.megabytes }
  
  validates :order_id, presence: true
  validates :unit_type, presence: true
  
end

app/controllers/admin/units_controller.rb
class Admin::UnitsController < ApplicationController
  before_action :admin_user
  
  def new
    @unit = Unit.new(order_id: params[:format])
  end

  def create
    @unit = Unit.new(unit_params)
    
    if @unit.save
      flash[:success] = "New unit created!"
      redirect_to @unit.order
    else
      flash[:warning] = "Creating failed.."
      render 'new'
    end
  end
  
  def edit
    @unit = Unit.find(params[:id])
  end
  
  def update
    @unit = Unit.find(params[:id])
    if @unit.update_attributes(unit_params)
      flash[:success] = "Unit updated"
      redirect_to @unit.order
    else
      render 'edit'
    end
  end
  
  def destroy
    @unit = Unit.find(params[:id])
    @unit.destroy
    flash[:success] = "Unit deleted."
    redirect_back_or order_path(@unit.order)
  end

  ########################
    def unit_params
      params.require(:unit).permit(:name, :content, :unit_type, :order_id, :img)
    end
  ########################
end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
  #before_action :correct_user_in_order
  
  #################################################
  def unit_params
    
  end
  
  def correct_user_in_order
     
  end
  #################################################
end

app/helpers/admin/units_helper.rb
module Admin::UnitsHelper
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/views/units/_thumb.html.erb
<ul class="thumb-unit">
  <% order.units.each do |unit| %>
  <li class="pull-left">
    <%= image_tag(unit.img.url(:thumb), alt: unit.unit_type, class: "unit") %>
  </li>
  <% end %>
</ul>

app/views/units/_unit.html.erb
<li>
  <div class="row">
    <div class="col-sm-4">
      <a href="#" class="thumbnail">
        <%= image_tag(unit.img.url(:medium), alt: unit.unit_type, class: "unit") %>
      </a>
    </div>

    <div class="col-sm-8">
      <div class="caption">
        <h3>
          <%= unit.name %>
          <% if current_user.admin? %>
            <%= link_to '수정', edit_admin_unit_path(unit), class: 'btn btn-sm btn-warning' %>
            <%= link_to '삭제', admin_unit_path(unit), method: :delete, class: 'btn btn-sm btn-danger', data: { confirm: 'Are you sure?' } %>
          <% end %>
        </h3>
        <p><%= unit.content %></p>
      </div>
    </div>
  </div>
</li>